export enum ErrorMessageCode {
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
	INVALID_TOKEN = "INVALID_TOKEN",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	ADMIN_ALREADY_EXISTS = "ADMIN_ALREADY_EXISTS",
	INCORRECT_EMAIL = "INCORRECT_EMAIL",
   

	ACCOUNT_DEACTIVATED_CONTACT_ADMINISTRATOR = "ACCOUNT_DEACTIVATED_CONTACT_ADMINISTRATOR",

	ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED",

	ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",

	SIGNUP_PROCESS_NOT_COMPLETED = "SIGNUP_PROCESS_NOT_COMPLETED",

	INVALID_OLD_PASSWORD = "INVALID_OLD_PASSWORD",

	OLD_NEW_SIMILAR_PASSWORD = "OLD_NEW_SIMILAR_PASSWORD",

	OLD_EMAIL = "OLD_EMAIL",

	RESET_PASSWORD_TOKEN_EXPIRED = "RESET_PASSWORD_TOKEN_EXPIRED",

	UPDATE_EMAIL_TOKEN_EXPIRED = "UPDATE_EMAIL_TOKEN_EXPIRED",


	DATA_NOT_FOUND = "DATA_NOT_FOUND",

	INSTRUCTOR_ALREADY_EXISTS = "INSTRUCTOR_ALREADY_EXISTS",

	ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND",

	TAG_NAME_EXISTS = "TAG_NAME_EXISTS",

	TAG_NOT_FOUND = "TAG_NOT_FOUND",

	PROMPT_ORDER_EXISTS = "PROMPT_ORDER_EXISTS",

	APP_NOT_SUPPORTED = "APP_NOT_SUPPORTED",

	PROMPT_NOT_FOUND = "PROMPT_NOT_FOUND",

	PROMOTIONAL_SCREENS_EXISTS = "PROMOTIONAL_SCREENS_EXISTS",

	PROMOTION_NOT_FOUND = "PROMOTION_NOT_FOUND",

	PROMOTION_UPDATE_TYPE_NOT_FOUND = "PROMOTION_UPDATE_TYPE_NOT_FOUND",

	RETRY_TOO_EARLY = "RETRY_TOO_EARLY",

	INVALID_OTP = "INVALID_OTP",

	TOO_MANY_LOGIN_ATTEMPTS = "TOO_MANY_ATTEMPTS",


	UNSUPPORTED_OAUTH_PROVIDER = "UNSUPPORTED_OAUTH_PROVIDER",



	DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND",

	PRICING_NOT_FOUND = "PRICING_NOT_FOUND",

	INSTRUCTOR_NOT_FOUND = "INSTRUCTOR_NOT_FOUND",

	PERMISSIONS_NOT_FOUND = "PERMISSIONS_NOT_FOUND",

	SUBSCRIPTION_PLAN_NOT_FOUND = "SUBSCRIPTIONPLAN_NOT_FOUND",

	APP_ID_NOT_FOUND = "INVALID_APP_ID",

	INSTRUCTOR_CATEGORIES_NOT_FOUND = "INSTRUCTOR_CATEGORIES_NOT_FOUND",

	ENTITY_ID_MISSING = "ENTITY_ID_MISSING",

	ENTITY_ID_NOT_FOUND = "ENTITY_ID_NOT_FOUND",

	INVALID_ENTITY_NAME = "INVALID_ENTITY_NAME",

	USER_HAS_ALREADY_TAKEN_TRIAL = "USER_HAS_ALREADY_TAKEN_TRIAL",

	USER_PAYMENT_ID_NOT_FOUND = "USER_PAYMENT_ID_NOT_FOUND",

	PAYMENT_INTENT_CREATION_FAILED = "PAYMENT_INTENT_CREATION_FAILED",

	PAYMENT_INTENT_FETCH_FAILED = "PAYMENT_INTENT_FETCH_FAILED",

	PAYMENT_INTENT_NOT_FOUND = "PAYMENT_INTENT_NOT_FOUND",

	PAYMENT_INTENT_STATUS_NOT_SUPPORTED = "PAYMENT_INTENT_STATUS_NOT_SUPPORTED",

	SUB_SCREEN_ID_NOT_FOUND = "SUBSCREEN_ID_NOT_FOUND",

	PROMPT_ORDER_NOT_FOUND = "PROMPT_ORDER_NOT_FOUND",

	INSTRUCTOR_NOT_ASSOCIATED_WITH_APP = "INSTRUCTOR_NOT_ASSOCIATED_WITH_APP",

	CATEGORY_NOT_ASSOCIATED_WITH_APP = "CATEGORY_NOT_ASSOCIATED_WITH_APP",

	TAGS_NOT_ASSOCIATED_WITH_APP = "TAGS_NOT_ASSOCIATED_WITH_APP",

	PAYMENT_INTENT_STATUS_UPDATE_FAILED = "PAYMENT_INTENT_STATUS_UPDATE_FAILED",

	INVALID_OPTIONS = "INVALID_OPTIONS",

	INVALID_ANSWER_ID = "INVALID_ANSWER_ID",

	QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND",

	USER_ANSWER_ALREADY_EXIST = "USER_ANSWER_ALREADY_EXIST",

	ACTIVATION_LINK_HAS_BEEN_EXPIRED = "ACTIVATION_LINK_HAS_BEEN_EXPIRED",

	ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",

	ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED",

	ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED",

	ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE",

	NEED_BOTH_HEIGHT_AND_WEIGHT = "NEED_BOTH_HEIGHT_AND_WEIGHT",

	TIME_SLOT_ALREADY_FILLED = "TIME_SLOT_ALREADY_FILLED",

	INVALID_ID = "INVALID_ID",

	EVENT_RATING_ALREADY_EXIST = "EVENT_RATING_ALREADY_EXIST",

	EVENT_ID_NOT_FOUND = "EVENT_ID_NOT_FOUND",

	EVENT_SHOULD_START_AFTER_SEVEN_DAYS = "EVENT_SHOULD_START_AFTER_SEVEN_DAYS",

	USER_MEAL_PLAN_NOT_FOUND = "USER_MEAL_PLAN_NOT_FOUND",

	USER_VOICE_ACTIVITY_NOT_FOUND = "USER_VOICE_ACTIVITY_NOT_FOUND",

	USER_MEAL_PLAN_NOTIFICATION_FAILED_TO_UPDATE = "USER_MEAL_PLAN_NOTI_FAILED_TO_UPDATE",

	QUESTIONNAIRE_INACTIVE = "QUESTIONNAIRE_INACTIVE",

	USER_INACTIVE = "USER_INACTIVE",

	QUESTIONARIES_NOT_FOUND = "QUESTIONARIES_NOT_FOUND",

	CONTENT_NOT_FOUND = "CONTENT_NOT_FOUND",

	INVALID_SORT_VALUE = "INVALID_SORT_VALUE",

	INSTRUCTOR_IS_NOT_A_MASTER = "INSTRUCTOR_IS_NOT_A_MASTER",

	INSTRUCTOR_IS_NOT_AFFIRMATED = "INSTRUCTOR_IS_NOT_AFFIRMATED",

	MISSING_DATE_TIME = "MISSING_DATE_TIME",

	INVALID_CATEGORY = "INVALID_CATEGORY",

	DAILY_GUIDED_CONTENT_EXISTS = "DAILY_GUIDED_CONTENT_EXISTS",

	PRICING_UPDATE_ONLY_FOR_VIDEO = "PRICING_UPDATE_ONLY_FOR_VIDEO",

	INACTIVE_INSTRUCTOR = "INACTIVE_INSTRUCTOR",

	NOT_A_DAILY_GUIDED_CONTENT = "NOT_A_DAILY_GUIDED_CONTENT",

	CATEGORY_DOES_NOT_EXIST = "CATEGORY_DOES_NOT_EXIST",

	JOURNAL_NOT_FOUND = "JOURNAL_NOT_FOUND",

	NOT_AFFIRMATED_BY_USER = "NOT_AFFIRMATED_BY_USER",

	EMAIL_DOES_NOT_EXIST = "EMAIL_DOES_NOT_EXIST",

	EITHER_ONE_REQUIRED = "EITHER_ONE_REQUIRED",

	BOTH_APPID_POSITION_REQUIRED = "BOTH_APPID_POSITION_REQUIRED",

	POSITION_NOT_FOUND = "POSITION_NOT_FOUND",

	ONBOARDING_QUESTION_NOT_FOUND = "ONBOARDING_QUESTION_NOT_FOUND",

	NO_ACTIVE_SUBSCRIPTIONS_PLANS = "NO_ACTIVE_SUBSCRIPTIONS_PLANS",

	INVALID_MODULE = "INVALID_MODULE",

	INVALID_FORMAT_TYPE = "INVALID_FORMAT_TYPE",

	EVENT_SHOULD_HAVE_AT_LEAST_ONE_SCHEDULE = "EVENT_SHOULD_HAVE_ATLEAST_ONE_SCHEDULE",

	NO_ACTIVE_EVENT_SCHEDULE = "NO_ACTIVE_EVENT_SCHEDULE",

	FORBIDDEN = "FORBIDDEN",

	INVALID_TIME_SLOT = "INVALID_TIME_SLOT",

	SUBSCRIPTION_PLAN_LIMIT_EXCEEDED = "SUBSCRIPTIONPLAN_LIMIT_EXCEEDED",

	SUBSCRIPTION_PLAN_NOT_FOR_DIET_PLAN = "SUBSCRIPTION_PLAN_NOT_FOR_DIET_PLAN",

	SUBSCRIPTION_PLAN_NOT_FOR_CHECK_IN_PLAN = "SUBSCRIPTION_PLAN_NOT_FOR_CHECK_IN_PLAN",

	INSUFFICIENT_DATA = "INSUFFICIENT_DATA",

	SOCIAL_MEDIA_LINK_NOT_FOUND = "SOCIAL_MEDIA_LINK_NOT_FOUND",

	QUALIFICATION_NOT_FOUND = "QUALIFICATION_NOT_FOUND",

	PATH_ID_NOT_FOUND = "PATH_ID_NOT_FOUND",

	FILE_NOT_FOUND = "FILE_NOT_FOUND",

	START_DATE_TIME_SHOULD_BE_GREATER_FROM_CURRENT_DATE_TIME = "START_DATE_TIME_SHOULD_BE_GREATER_FROM_CURRENT_DATE_TIME",

	END_DATE_TIME_RANGE_EXCEEDED = "END_DATE_TIME_RANGE_EXCEEDED",

	NOT_A_SERIES_CONTENT = "NOT_A_SERIES_CONTENT",

	EPISODE_NOT_FOUND = "EPISODE_NOT_FOUND",

	INVALID_CONTENT_TYPE_UPDATE = "INVALID_CONTENT_TYPE_UPDATE",

	DGC_ONLY_FOR_AUDIO_VIDEO = "DGC_ONLY_FOR_AUDIO_VIDEO",

	MISMATCH_TIME_PATTERN = "MISMATCH_TIME_PATTERN",

	NOT_A_CONTENT = "NOT_A_CONTENT",

	EITHER_ONE_URL = "EITHER_ONE_URL",

	INSTRUCTOR_ALREADY_ASSOCIATED = "INSTRUCTOR_ALREADY_ASSOCIATED",

	ADMIN_ALREADY_ASSOCIATED = "ADMIN_ALREADY_ASSOCIATED",

	YOUR_ACCOUNT_ALREADY_SIGNED_UP = "YOUR_ACCOUNT_ALREADY_SIGNED_UP",

	ACCESS_DENIED = "ACCESS_DENID",

	REPORT_DATE_MIN_ERROR = "REPORT_DATE_MIN_ERROR",

	ANURA_SESSION_ID = "ANURA_SESSION_ID",

	ANURA_SCAN_AWAITING = "ANURA_SCAN_AWAITING",

	ANURA_SCAN_CANCELLED = "ANURA_SCAN_CACELLED",

	ANURA_REPORT_EXIST = "ANURA_REPORT_EXIST",

	AT_LEAST_1_SUB_SCREEN_NEEDED = "ATLEAST_A_SUBSCREEN_NEEDED",

	CANT_BE_FAVOURITED = "CANT_BE_FAVOURITED",

	NOTIFICATION_TEMPLATE_NOT_FOUND = "NOTIFICATION_TEMPLATE_NOT_FOUND",

	NOTIFICATION_DELIVERY_METHOD_NOT_SUPPORTED = "NOTIFICATION_DELIVERY_METHOD_NOT_SUPPORTED",

	SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR",

	CURRENTLY_NO_TAGS = "CURRENLTY_NO_TAGS",

	NOT_A_MASTER = "NOT_A_MASTER",

	USER_EMAIL_NOT_FOUND = "USER_EMAIL_NOT_FOUND",

	// COMMON
	RECORD_NOT_FOUND = "RECORD_NOT_FOUND",

	TYPE_NOT_FOUND = "TYPE_NOT_FOUND",

	RESULT_NOT_FOUND = "RESULT_NOT_FOUND",

	UNABLE_TO_DELETE = "UNABLE_TO_DELETE",

	TOO_MANY_INVALID_RETRY = "TOO_MANY_INVALID_RETRY",

	TAGS_NOT_ASSOCIATED = "TAGS_NOT_ASSOCIATED",

	OPTION_IS_MAPPED = "OPTION_IS_MAPPED",

	OPTION_NOT_FOUND = "OPTION_NOT_FOUND",

	PURCHASE_OPTION_NOT_FOUND = "PURCHASE_OPTION_NOT_FOUND",

	UNSUPPORTED_CURRENCY_TYPE = "UNSUPPORTED_CURRENCY_TYPE",

	INSTRUCTOR_IS_REQUIRED = "INSTRUCTOR_IS_REQUIRED",

	THIRD_PARTY_ERROR = "THIRD_PARTY_ERROR",

	PAYMENT_PLAN_NOT_FOUND = "PAYMENT_PLAN_NOT_FOUND",

	USER_DOB_NOT_FOUND = "USER_DOB_NOT_FOUND",

	USER_GENDER_NOT_FOUND = "USER_GENDER_NOT_FOUND",

	USER_WEIGHT_NOT_FOUND = "USER_WEIGHT_NOT_FOUND",

	USER_HEIGHT_NOT_FOUND = "USER_HEIGHT_NOT_FOUND",

	ACTIVE_SUBSCRIPTION_NOT_FOUND = "ACTIVE_SUBSCRIPTION_NOT_FOUND",

	USER_FIRST_LOOK_REPORT_NOT_FOUND = "USER_FIRST_LOOK_REPORT_NOT_FOUND",

	ALREADY_FAVOURITED = "ALREADY_FAVOUITED",

	ALREADY_AFFIRMATED = "ALREADY_AFFIRMATED",

	SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND",

	INVALID_APP = "INVALID_APP",

	ANSWER_TAG_NOT_FOUND = "ANSWER_TAG_NOT_FOUND",

	USER_ALREADY_TAKEN_EVENT = "USER_ALREADY_TAKEN_EVENT",

	SUBSCRIPTION_NOT_ACTIVE = "SUBSCRIPTION_NOT_ACTIVE",

	ACCOUNT_NOT_VERIFIED_IN_APPLE = "ACCOUNT_NOT_VERIFIED_IN_APPLE",

	INVALID_STATISTICS_CATEGORY = "INVALID_STATITICS_CATEGORY",

	EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",

	PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS",

	ALREADY_ASSOCIATED_WITH_PHONE = "ALREADY_ASSOCIATED_WITH_PHONE",

	ALREADY_ASSOCIATED_WITH_EMAIL = "ALREADY_ASSOCIATED_WITH_EMAIL",

	AGE_OUT_OF_RANGE = "AGE_OUT_OF_RANGE",

	HEIGHT_OUT_OF_RANGE = "HEIGHT_OUT_OF_RANGE",

	WEIGHT_OUT_OF_RANGE = "WEIGHT_OUT_OF_RANGE",

	WAIST_OUT_OF_RANGE = "WAIST_OUT_OF_RANGE",

	SYSTOLIC_OUT_OF_RANGE = "SYSTOLIC_OUT_OF_RANGE",

	DIASTOLIC_OUT_OF_RANGE = "DIASTOLIC_OUT_OF_RANGE",

	LOGOUT_FROM_ANOTHER_DEVICE = "LOGOUT_FROM_ANOTHER_DEVICE",

	YOU_CANNOT_APPROVE_EXPIRED_TIME_EVENT = "YOU_CANNOT_APPROVE_EXPIRED_TIME_EVENT",

	ADDRESS_ALREADY_EXISTS = "ADDRESS_ALREADY_EXISTS",

	INVALID_PROMO_CODE = "INVALID_PROMO_CODE",

	DUPLICATE_PROMO_CODE = "DUPLICATE_PROMO_CODE",

	COUPON_CODE_INVALID = "COUPON_CODE_INVALID",

	COUPON_CODE_EXPIRED = "COUPON_CODE_EXPIRED",

	INVALID_PLAN_TYPE = "INVALID_PLAN_TYPE",


}