export enum ActivityTypeEnum {
	LOGIN = "LOGIN",
	WELLNESS_STAT = "WELLNESS_STAT",
}

export enum BoRoleEnum {
	SUPER_ADMIN = "SUPER_ADMIN",
	ADMIN = "ADMIN",
	EXECUTIVE = "EXECUTIVE",
}

export enum BoUserStatus {
	INVITE_PENDING = "INVITE_PENDING",
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	DELETED = "DELETED",
}

export enum CategoryTypeEnum {
	DAILY_GUIDED_CONTENT = "DAILY_GUIDED_CONTENT",
	EPISODES = "EPISODES",
	AFFIRMATION = "AFFIRMATION",
	FAVOURITES = "FAVOURITES",
	WATCHED = "WATCHED",
}

export enum ContentTypeEnum {
	AUDIO = "AUDIO",
	VIDEO = "VIDEO",
	TEXT = "TEXT",
	SERIES = "SERIES",
}
export enum seriesTypeEnum {
	INTERNAL = "INTERNAL",
	YOUTUBE = "YOUTUBE",
	VIDEO = "VIDEO",
	AUDIO = "AUDIO",
}
export enum CurrencyCodeEnum {
	USD = "USD",
	INR = "INR",
}

export enum DashboardMetricsEnum {
	ACTIVE_USER = "ACTIVE_USER",
	INACTIVE_USER = "INACTIVE_USER",
	ACTIVE_HOST = "ACTIVE_HOST",
	INACTIVE_HOST = "INACTIVE_HOST",
	REVENUE_GENERATOR = "REVENUE_GENERATOR",
}

export enum DayEnum {
	SUNDAY = "SUNDAY",
	MONDAY = "MONDAY",
	TUESDAY = "TUESDAY",
	WEDNESDAY = "WEDNESDAY",
	THURSDAY = "THURSDAY",
	FRIDAY = "FRIDAY",
	SATURDAY = "SATURDAY",
}

export enum EventParticipantStatusEnum {
	PAYMENT_PENDING = "PAYMENT_PENDING",
	PAYMENT_FAILED = "PAYMENT_FAILED",
	ACTIVE = "ACTIVE",
	CANCELLED = "CANCELLED",
}

export enum PAYMENT_GATEWAYS {
	STRIPE = "stripe",
	RAZORPAY = "razorpay",
}

export enum PaymentStatusEnum {
	/**
	 * Payment is paid
	 */
	PAYMENT_PAID = "PAYMENT_PAID",

	/**
	 * Payment is pending
	 */
	PAYMENT_PENDING = "PAYMENT_PENDING",

	/**
	 * Payment has failed
	 */
	PAYMENT_FAILED = "PAYMENT_FAILED",

	/**
	 * Payment has been cancelled by payer
	 */
	PAYMENT_CANCELLED = "PAYMENT_CANCELLED",

	/**
	 * Payment request expired
	 */
	PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
}

export enum EventStatusEnum {
	APPROVAL_PENDING = "APPROVAL_PENDING",
	REJECTED = "REJECTED",
	PUBLISHED = "PUBLISHED",
	YET_TO_START = "YET_TO_START",
	ACTIVE = "ACTIVE",
	COMPLETED = "COMPLETED",
	CANCELLED = "CANCELLED",
	YET_TO_PUBLISH = "YET_TO_PUBLISH",
	UPCOMING = "UPCOMING",
}

export enum EventTypeEnum {
	LIVE_EVENT = "LIVE_EVENT",
	WORKSHOP = "WORKSHOP",
	CONSULTATION = "CONSULTATION",
}

export enum GenderEnum {
	M = "M",
	F = "F",
	O = "O",
}

export enum CouponTypeEnum {
	PERCENTAGE = "PERCENTAGE",
	AMOUNT = "AMOUNT",
}

export enum CouponStatusEnum {
	ENABLED = "ENABLED",
	DISABLED = "DISABLED",
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	CLOSED = "CLOSED",
}

export enum HostAccountStatusEnum {
	INVITE_PENDING = "INVITE_PENDING",
	APPROVAL_PENDING = "APPROVAL_PENDING",
	ACTIVATION_PENDING = "ACTIVATION_PENDING",
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	DELETE = "DELETE",
	DECLINE = "DECLINE",
}

export enum HostStatusEnum {
	REMOVED = "REMOVED",
	ACTIVE = "ACTIVE",
	JOINED = "JOINED",
	LEFT = "LEFT",
}

export enum IntervalEnum {
	EARLY_MORNING = "EARLY_MORNING",
	BREAKFAST = "BREAKFAST",
	MID_MEAL = "MID_MEAL",
	MID_MORNING_SNACK = "MID_MORNING_SNACK",
	LUNCH = "LUNCH",
	SNACKS = "SNACKS",
	DINNER = "DINNER",
	BED_TIME = "BED_TIME",
}

export enum IntervalTypeEnum {
	DAY = "DAY",
	MONTH = "MONTH",
}

export enum JournalTypeEnum {
	SELF = "SELF",
	GUIDED = "GUIDED",
}

export enum MealPlanTypeEnum {
	FOOD_TAKEN = "FOOD_TAKEN",
}

export enum NewEmailVerificationStatusEnum {
	PENDING_VERIFICATION = "PENDING_VERIFICATION",
	VERIFIED = "VERIFIED",
}

/**
 * Notification Template Content Type
 * The type of content that the notification template will be used for
 *
 * TODO: drive this from DB
 */
export enum NotificationTemplateContentTypeEnum {
	SYSTEM = "SYSTEM",
	TRANSACTIONAL = "TRANSACTIONAL",
	REMAINDER = "REMAINDER",
	REMINDER = "REMINDER",
	MARKETING = "MARKETING",
}

export enum NotificationDeliveryMethodEnum {
	EMAIL = "EMAIL",
	SMS = "SMS",
	PUSH = "PUSH",
	INAPP = "INAPP",
}

/**
 * The status of the notification delivery
 */
export enum NotificationDeliveryStatusEnum {
	/**
	 * The notification has been requested to be sent
	 */
	REQUESTED = "REQUESTED",

	/**
	 * The notification has been sent
	 */
	SENT = "SENT",

	/**
	 * The notification has been delivered
	 */
	DELIVERED = "DELIVERED",

	/**
	 * The notification has failed to be sent
	 */
	FAILED = "FAILED",
}

/**
 * The template rendering engine to be used for rendering the notification template
 */
export enum NotificationRenderTypeEnum {
	EJS = "EJS",
	NONE = "NONE",
}

export enum NotifyTemplate {
	// ASSESSMENT
	AFFIRMATION_DUE = "AFFIRMATION_DUE",
	MEAL_NOTIFICATION = "MEAL_NOTIFICATION",

	// EVENTS
	EVENT_ACTIVATE = "EVENT_ACTIVATE",
	EVENT_AUTO_CANCEL = "EVENT_AUTO_CANCEL",
	EVENT_REMINDER = "EVENT_REMINDER",
	EVENT_REPOST = "EVENT_REPOST",
	EVENT_SCHEDULE_CANCELLED_BY_SYSTEM = "EVENT_SCHEDULE_CANCELLED_BY_SYSTEM",
	EVENT_CANCELLED_BY_ADMIN = "EVENT_CANCELLED_BY_ADMIN",
	EVENT_CANCELLED_FOR_CUSTOMER = "EVENT_CANCELLED_FOR_CUSTOMER",
	EVENT_SLOT_CHANGE = "EVENT_SLOT_CHANGE",
	EVENT_STATUS_CHANGE = "EVENT_STATUS_CHANGE",

	// SUBSCRIPTION
	SUBSCRIPTION_REMINDER_FAR = "SUBSCRIPTION_REMINDER_FAR",
	SUBSCRIPTION_REMINDER_NEAR = "SUBSCRIPTION_REMINDER_NEAR",
	SUBSCRIPTION_REMINDER_TODAY = "SUBSCRIPTION_REMINDER_TODAY",
	SUBSCRIPTION_AUTO_CANCELLED = "SUBSCRIPTION_AUTO_CANCELLED",
	SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED",

	// PAYMENT
	PURCHASED_SUBSCRIPTION = "PURCHASED_SUBSCRIPTION",
	PURCHASED_ONE_TIME_ITEM = "PURCHASED_ONE_TIME_ITEM",
	PURCHASED_EVENT_TRIAL = "PURCHASED_EVENT_TRIAL",
	PURCHASED_EVENT_ONE_TIME = "PURCHASED_EVENT_ONE_TIME",
	PURCHASED_EVENT_SUBSCRIPTION = "PURCHASED_EVENT_SUBSCRIPTION",

	// SYSTEM
	TEMPLATE = "TEMPLATE",
	FORGOT_PASSWORD = "FORGOT_PASSWORD",
	LOGIN_OTP = "LOGIN_OTP",
	SIGNUP_OTP = "SIGNUP_OTP",
	INVITE_ADMIN_OR_EXECUTIVE = "INVITE_ADMIN_OR_EXECUTIVE",
	UPDATE_EMAIL = "UPDATE_EMAIL",
	INVITE_INSTRUCTOR = "INVITE_INSTRUCTOR",
	VERIFY_EMAIL = "VERIFY_EMAIL",
	CONTACT_US = "CONTACT_US",
	ACCOUNT_STATUS = "ACCOUNT_STATUS",
	EVENT_BOOKING_CONFIRMATION = "EVENT_BOOKING_CONFIRMATION",
	VERIFY_NEW_PHONE_NUMBER = "VERIFY_NEW_PHONE_NUMBER",
	NOTIFICATION_WELCOME = "NOTIFICATION_WELCOME",
	DAILY_CRON_HEALTH_REPORT = "DAILY_CRON_HEALTH_REPORT",
	REPORT_EXPORT = "REPORT_EXPORT",
}

export enum BoUserPermissionEnum {
	ALL_ACCESS = "ALL_ACCESS",
	DASHBOARD = "DASHBOARD",
	ADMIN_VIEW = "ADMIN_VIEW",
	ADMIN_EDIT = "ADMIN_EDIT",
	ASSIGN_ADMIN = "ASSIGN_ADMIN",
	CMS_VIEW = "CMS_VIEW",
	CMS_EDIT = "CMS_EDIT",
	THINK_RIGHT = "THINK_RIGHT",
	EAT_RIGHT = "EAT_RIGHT",
	MOVE_RIGHT = "MOVE_RIGHT",
	SLEEP_RIGHT = "SLEEP_RIGHT",
	CUSTOMER_VIEW = "CUSTOMER_VIEW",
	CUSTOMER_EDIT = "CUSTOMER_EDIT",
	HOST_VIEW = "HOST_VIEW",
	HOST_APPROVE = "HOST_APPROVE",
	HOST_EDIT = "HOST_EDIT",
	EVENT_VIEW = "EVENT_VIEW",
	EVENT_EDIT = "EVENT_EDIT",
	PRICING_VIEW = "PRICING_VIEW",
	PRICING_EDIT = "PRICING_EDIT",
}

export enum PricingCategoryEnum {
	DIET_PLAN = "DIET_PLAN",
	HEALTH_REPORT = "HEALTH_REPORT",
	FACIAL_SCAN = "FACIAL_SCAN",
	CHECK_IN = "CHECK_IN",
	PAID_TRIAL_CLASS = "PAID_TRAIL_CLASS",
	LIVE_CLASS = "LIVE_CLASS",
	PAID_TRIAL_CLASS_24 = "PAID_TRAIL_CLASS_24",
	LIVE_CLASS_24 = "LIVE_CLASS_24",
	AFFIRMATION = "AFFIRMATION",
	PAID_CONTENT = "PAID_CONTENT",
	BUNDLE_OFFERING = "BUNDLE_OFFERING",
	THINKRIGHT_ASSESSMENT = "THINKRIGHT_ASSESSMENT",
	SLEEPRIGHT_ASSESSMENT = "SLEEPRIGHT_ASSESSMENT",
    WORKSHOP = "WORKSHOP"
}

export enum PromotionContentTypeEnum {
	AUDIO = "AUDIO",
	VIDEO = "VIDEO",
	IMAGE = "IMAGE",
}

export enum PromotionSubScreen {
	TOP = "TOP",
	MIDDLE = "MIDDLE",
	BOTTOM = "BOTTOM",
	ASSESSMENT_FORM = "ASSESSMENT_FORM",
	FIRST_LOOK_REPORT = "FIRST_LOOK_REPORT",
	FACIAL_SCAN = "FACIAL_SCAN",
}

export enum PromotionUpdateType {
	PROMOTION = "PROMOTION",
	STATUS = "STATUS",
}

export enum PricingEnum {
	PAID = "PAID",
	FREE = "FREE",
}

export enum SubscriptionCategoryEnum {
	ONE_TIME = "ONE_TIME",
	SUBSCRIPTION = "SUBSCRIPTION",
	BUNDLE = "BUNDLE",
}

export enum PurchaseOptionsEnum {
	DIET_PLAN = "DIET_PLAN",
	HEALTH_REPORT = "HEALTH_REPORT",
	CHECK_IN = "CHECK_IN",
	FACIAL_SCAN = "FACIAL_SCAN",

	LIVE_CLASS = "LIVE_CLASS",
	LIVE_CLASS_24 = "LIVE_CLASS_24",
	PAID_TRIAL_LIVE_CLASS = "PAID_TRAIL_LIVE_CLASS",
	PAID_TRIAL_LIVE_CLASS_24 = "PAID_TRAIL_LIVE_CLASS_24",
	WORKSHOP = "WORKSHOP",
	CONSULTATION = "CONSULTATION",

	AFFIRMATION = "AFFIRMATION",
	PAID_CONTENT = "PAID_CONTENT",
	CURATED_YOGA = "CURATED_YOGA",
	FREE_ASSESSMENT = "FREE_ASSESSMENT",
	SUBSCRIPTION_PLAN = "SUBSCRIPTION_PLAN",
}

export enum PurchaseOptionsPlanEnum {
	// DIET_PLAN
	DIET_PLAN_ONE_TIME = "DIET_PLAN_ONE_TIME",
	DIET_PLAN_SUBSCRIPTION = "DIET_PLAN_SUBSCRIPTION",
	DIET_PLAN_BUNDLE = "DIET_PLAN_BUNDLE",
	// HEALTH_REPORT
	HEALTH_REPORT_ONE_TIME = "HEALTH_REPORT_ONE_TIME",
	HEALTH_REPORT_SUBSCRIPTION = "HEALTH_REPORT_SUBSCRIPTION",
	HEALTH_REPORT_BUNDLE = "HEALTH_REPORT_BUNDLE",
	// CHECK_IN
	CHECK_IN_ONE_TIME = "CHECK_IN_ONE_TIME",
	CHECK_IN_SUBSCRIPTION = "CHECK_IN_SUBSCRIPTION",
	CHECK_IN_BUNDLE = "CHECK_IN_BUNDLE",
	// FACIAL_SCAN
	FACIAL_SCAN_ONE_TIME = "FACIAL_SCAN_ONE_TIME",
	FACIAL_SCAN_SUBSCRIPTION = "FACIAL_SCAN_SUBSCRIPTION",
	FACIAL_SCAN_BUNDLE = "FACIAL_SCAN_BUNDLE",
	// CONTENT
	AFFIRMATION_ONE_TIME = "AFFIRMATION_ONE_TIME",
	AFFIRMATION_SUBSCRIPTION = "AFFIRMATION_SUBSCRIPTION",
	AFFIRMATION_BUNDLE = "AFFIRMATION_BUNDLE",
	PAID_CONTENT_ONE_TIME = "PAID_CONTENT_ONE_TIME",
	PAID_CONTENT_SUBSCRIPTION = "PAID_CONTENT_SUBSCRIPTION",
	PAID_CONTENT_BUNDLE = "PAID_CONTENT_BUNDLE",
}

export enum QuestionaryStatusEnum {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
}

export enum QuestionaryTypeEnum {
	THINKRIGHT_ASSESSMENT = "THINKRIGHT_ASSESSMENT",
	SLEEPRIGHT_ASSESSMENT = "SLEEPRIGHT_ASSESSMENT",
	DIET_PLAN = "DIET_PLAN",
	HEALTH_REPORT = "HEALTH_REPORT",
	CHECK_IN = "CHECK_IN",
	FACIAL_SCAN = "FACIAL_SCAN",
}

export enum QuestionaryInputEnum {
	/**
	 * Simple text input
	 */
	TEXT = "TEXT",

	/*
	 * number input
	 */
	NUMBER = "NUMBER",

	/*
	 * Select input
	 */
	SELECT = "SELECT",

	/*
	 * Radio input
	 */
	RADIO = "RADIO",

	/*
	 * Multi select checkbox
	 */
	CHECK_BOX = "CHECK_BOX",

	/*
	 * Sonde Audio URL Upload Widget
	 */
	AUDIO_URL = "AUDIO_URL",

	/**
	 * Expandable panel
	 */
	EXPANSION_PANEL = "EXPANSION_PANEL",
}

export enum SocialMediaEnum {
	FACEBOOK = "FACEBOOK",
	INSTAGRAM = "INSTAGRAM",
	LINKEDIN = "LINKEDIN",
}

export enum StaticContentEnum {
	PRIVACY_POLICY = "PRIVACY_POLICY",
	TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS",
	FAQS = "FAQS",
	CONTACT_US = "CONTACT_US",
	ABOUT_US = "ABOUT_US",
}

export enum SubscriptionDurationEnum {
	ONE_TIME = "ONE_TIME",
	DAY = "DAY",
	WEEK = "WEEK",
	MONTH = "MONTH",
	QUARTER = "QUARTER",
	HALF_YEAR = "HALF_YEAR",
	YEAR = "YEAR",
	INFINITE = "INFINITE",
}

export enum SubscriptionPlanType {
	ONE_TIME = "ONE_TIME",
	MONTH = "MONTH",
	YEAR = "YEAR",
	PACK_12_YEAR = "PACK_12_YEAR",
	PACK_36_YEAR = "PACK_36_YEAR",
	PAID_TRIAL_ONE_TIME = "PAID_TRIAL_ONE_TIME",
}

export enum SubscriptionPlanName {
	ONE_TIME = "One Time",
	MONTH = "Monthly",
	YEAR = "Yearly",
	PACK_12_YEAR = "12 Yearly",
	PACK_36_YEAR = "36 Yearly",
	PAID_TRIAL_ONE_TIME = "Paid Trial - One Time",
}

export enum SubscriptionStatusEnum {
	PAYMENT_INPROGRESS = "PAYMENT_INPROGRESS",
	PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
	ACTIVE = "ACTIVE",
	EXPIRED = "EXPIRED",
	CANCELLED = "CANCELLED",
}

export enum SubscriptionTypesEnum {
	WORKSHOP = "WORKSHOP",
	CONSULTATION = "CONSULTATION",
	LIVE_CLASS_COMPLETE = "LIVECLASS_COMPLETE",
	LIVE_CLASS_TRIAL = "LIVECLASS_TRAIL",
}

export enum TagStatusEnum {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
}

export enum CouponDurationEnum {
	MONTH = "MONTH",
	YEAR = "YEAR",
}

export enum ThirdPartyEnum {
	MEAL_PALN = "MEAL_PALN",
	HEALTH_REPORT = "HEALTH_REPORT",
	VONAGE = "VONAGE",
	CHECK_IN = "CHECK_IN",
}

export enum UserAnswerStatusEnum {
	PAYMENT_INPROGRESS = "PAYMENT_INPROGRESS",
	RESULT_AWAITING = "RESULT_AWAITING",
	INSUFFICIENT_DATA = "INSUFFICIENT_DATA",
	SUCCESS = "SUCCESS",
	PAYMENT_FAILURE = "PAYMENT_FAILURE",
	ERROR = "ERROR",
}


export enum UserStatusEnum {
    ACTIVATION_PENDING = "ACTIVATION_PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    DELETE = "DELETE",
    ISDELETED = "ISDELETED"
}

export enum CustomerStatusEnum {
  isDeleted = "isDeleted",

}

export enum VendorEnum {
	VONAGE = "VONAGE",
}

export enum AppTypeId {
	// home
	HOME_DAILY_GUIDED_CONTENT = "HOME_DAILY_GUIDED_CONTENT",
	// sleep
	SLEEP_RIGHT_SLEEP_SOUNDS = "SLEEP_RIGHT_SLEEP_SOUNDS",
	SLEEP_RIGHT_SLEEP_SOUNDS_SUB1 = "SLEEP_RIGHT_SLEEP_SOUNDS_SUB1",
	SLEEP_RIGHT_SLEEP_SOUNDS_SUB2 = "SLEEP_RIGHT_SLEEP_SOUNDS_SUB2",
	SLEEP_RIGHT_SLEEP_SOUNDS_SUB3 = "SLEEP_RIGHT_SLEEP_SOUNDS_SUB3",
	SLEEP_RIGHT_SLEEP_SOUNDS_SUB4 = "SLEEP_RIGHT_SLEEP_SOUNDS_SUB4",
	SLEEP_RIGHT_SLEEP_SOUNDS_SUB5 = "SLEEP_RIGHT_SLEEP_SOUNDS_SUB5",

	SLEEP_RIGHT_SLEEP_HYGEINE = "SLEEP_RIGHT_SLEEP_HYGEINE",
	SLEEP_RIGHT_SLEEP_DISORDERS = "SLEEP_RIGHT_SLEEP_DISORDERS",
	SLEEP_RIGHT_SLEEP_AND_MENTAL_HEALTH = "SLEEP_RIGHT_SLEEP_AND_MENTAL_HEALTH",
	SLEEP_RIGHT_SLEEP_AND_CHRONIC_HEALTH_CONDITIONS = "SLEEP_RIGHT_SLEEP_AND_CHRONIC_HEALTH_CONDITIONS",
	SLEEP_RIGHT_SLEEP_AND_PERFORMANCE = "SLEEP_RIGHT_SLEEP_AND_PERFORMANCE",
	SLEEP_RIGHT_SLEEP_AND_AGE = "SLEEP_RIGHT_SLEEP_AND_AGE",
	// move
	MOVE_RIGHT_YOGA = "MOVE_RIGHT_YOGA",
	MOVE_RIGHT_MOVEMENT = "MOVE_RIGHT_MOVEMENT",
	MOVE_RIGHT_BREATHING_EXERCISES = "MOVE_RIGHT_BREATHING_EXERCISES",
	MOVE_RIGHT_INCLUSIVE_FITNESS = "MOVE_RIGHT_INCLUSIVE_FITNESS",
	MOVE_RIGHT_REHABILITATION = "MOVE_RIGHT_REHABILITATION",
	MOVE_RIGHT_AGING = "MOVE_RIGHT_AGING",
	// eat
	EAT_RIGHT_RECIPE = "EAT_RIGHT_RECIPE",
	EAT_RIGHT_RECIPE_SUB1 = "EAT_RIGHT_RECIPE_SUB1",
	EAT_RIGHT_RECIPE_SUB2 = "EAT_RIGHT_RECIPE_SUB2",
	EAT_RIGHT_RECIPE_SUB3 = "EAT_RIGHT_RECIPE_SUB3",
	EAT_RIGHT_RECIPE_SUB4 = "EAT_RIGHT_RECIPE_SUB4",
	EAT_RIGHT_RECIPE_SUB5 = "EAT_RIGHT_RECIPE_SUB5",

	EAT_RIGHT_EXPERT_VIDEOS = "EAT_RIGHT_EXPERT_VIDEOS",
	EAT_RIGHT_FOOD_AND_MIND = "EAT_RIGHT_FOOD_AND_MIND",
	EAT_RIGHT_FOOD_AND_BODY = "EAT_RIGHT_FOOD_AND_BODY",
	EAT_RIGHT_WOMEN_HEALTH = "EAT_RIGHT_WOMEN_HEALTH",
	EAT_RIGHT_ALTERNATIVE_DIET = "EAT_RIGHT_ALTERNATIVE_DIET",
	EAT_RIGHT_NUTRIENTS_AND_FOOD = "EAT_RIGHT_NUTRIENTS_AND_FOOD",
	EAT_RIGHT_HYDRATION = "EAT_RIGHT_HYDRATION",
	EAT_RIGHT_HEALING = "EAT_RIGHT_HEALING",
	EAT_RIGHT_ALLERGIES = "EAT_RIGHT_ALLERGIES",
	EAT_RIGHT_RECIPES = "EAT_RIGHT_RECIPES",
	// think
	THINK_RIGHT_MEDITATION = "THINK_RIGHT_MEDITATION",
	THINK_RIGHT_MEDITATION_SUB1 = "THINK_RIGHT_MEDITATION_SUB1",
	THINK_RIGHT_MEDITATION_SUB2 = "THINK_RIGHT_MEDITATION_SUB2",
	THINK_RIGHT_MEDITATION_SUB3 = "THINK_RIGHT_MEDITATION_SUB2",
	THINK_RIGHT_MEDITATION_SUB4 = "THINK_RIGHT_MEDITATION_SUB2",
	THINK_RIGHT_MEDITATION_SUB5 = "THINK_RIGHT_MEDITATION_SUB2",

	THINK_RIGHT_PEACE = "THINK_RIGHT_PEACE",
	THINK_RIGHT_SELF_HEALING = "THINK_RIGHT_SELF_HEALING",
	THINK_RIGHT_RELATIONSHIPS = "THINK_RIGHT_RELATIONSHIPS",
	THINK_RIGHT_SELF_GROWTH = "THINK_RIGHT_SELF_GROWTH",
	THINK_RIGHT_SUCCESS = "THINK_RIGHT_SUCCESS",
	THINK_RIGHT_MEDITATION_BASIS = "THINK_RIGHT_MEDITATION_BASIS",
	THINK_RIGHT_BASIC_OF_AFFIRMATIONS = "THINK_RIGHT_BASIC_OF_AFFIRMATIONS",
	THINK_RIGHT_DAILY_AFFIRMATION = "THINK_RIGHT_DAILY_AFFIRMATION",
	THINK_RIGHT_COPING = "THINK_RIGHT_COPING",
	THINK_RIGHT_EMOTIONAL_INTELLIGENCE = "THINK_RIGHT_EMOTIONAL_INTELLIGENCE",
	THINK_RIGHT_MENTAL_GYM = "THINK_RIGHT_MENTAL_GYM",
	THINK_RIGHT_MIND_AND_BODY = "THINK_RIGHT_MIND_AND_BODY",
	THINK_RIGHT_STRESS_MANAGEMENT = "THINK_RIGHT_STRESS_MANAGEMENT",
	THINK_RIGHT_CULTURE_AND_DIVERSITY = "THINK_RIGHT_CULTURE_AND_DIVERSITY",
	THINK_RIGHT_DIGITAL_WELL_BEING = "THINK_RIGHT_DIGITAL_WELL_BEING",
	// event
	EVENT_LEVEL_BEGINNER = "EVENT_LEVEL_BEGINNER",
	EVENT_LEVEL_INTERMEDIATE = "EVENT_LEVEL_INTERMEDIATE",
	EVENT_LEVEL_EXPERT = "EVENT_LEVEL_EXPERT",

	EVENT_MOVE_RIGHT_VINYASA = "EVENT_MOVE_RIGHT_VINYASA",
	EVENT_MOVE_RIGHT_HATHA = "EVENT_MOVE_RIGHT_HATHA",
	EVENT_MOVE_RIGHT_POWER = "EVENT_MOVE_RIGHT_POWER",
}

export enum AppId {
	THINK_RIGHT = "THINK_RIGHT",
	SLEEP_RIGHT = "SLEEP_RIGHT",
	MOVE_RIGHT = "MOVE_RIGHT",
	EAT_RIGHT = "EAT_RIGHT",
	HOME_PAGE = "HOME_PAGE",
	ECOMMERCE = "ECOMMERCE",
	MY_HEALTH = "MY_HEALTH",
	ALL = "ALL",
	GENERAL = "GENERAL",
}

export enum AppTypeService {
	CONTENT = "CONTENT",
	EVENT = "EVENT",
}

export enum AppTypeType {
	CATEGORY = "CATEGORY",
	SUB_CATEGORY = "SUB_CATEGORY",
}

export enum navigationScreen {
	HOME_PAGE = "HOME_PAGE",
	SELF_ASSESSMENT = "SELF_ASSESSMENT",
	VOICE_SCAN = "VOICE_SCAN",
	CONTENT = "CONTENT",
	JOURNAL = "JOURNAL",
	AFFIRMATIONS = "AFFIRMATIONS",
	WORKSHOP = "WORKSHOP",
	STORE = "STORE",
	DIET_PLAN = "DIET_PLAN",
	SELF_ASSESSMENT_FORM = "SELF_ASSESSMENT_FORM",
	SLEEP_SOUND = "SLEEP_SOUND",
	LIVE_CLASS = "LIVE_CLASS",
	FACIAL_SCAN = "FACIAL_SCAN",
	FIRST_LOOK_REPORT = "FIRST_LOOK_REPORT",
	THINK_ASSESSMENT_FORM = "THINK_ASSESSMENT_FORM",
}

export enum UserMealPlanActivity {
	SUCCESS = "SUCCESS",
}

export enum LengthUnitEnum {
	CM = "CM",
	INCH = "INCH",
}

export enum WeightUnitEnum {
	KG = "KG",
	LBS = "LBS",
}

export enum UrlType {
	PROFILE = "profile",
	CONTENT = "content",
	PROMOTION = "promotion",
}

export enum FormatType {
	JPG = "jpg",
	JPEG = "jpeg",
	PNG = "png",
	MP4 = "mp4",
}

export enum VoiceActivityEnum {
	CREATED = "CREATED",
	UPLOADED = "UPLOADED",
	AWAITING_RESULT = "AWAITING_RESULT",
	SUCCESS = "SUCCESS",
	ERROR = "ERROR",
}

export enum InstructorCategories {
	MINDFULNESS_MEDITATION = "MINDFULNESS_MEDITATION",
	SPIRITUAL_MEDITATION = "SPIRITUAL_MEDITATION",
	FOCUSED_MEDITATION = "FOCUSED_MEDITATION",
	MOVEMENT_MEDITATION = "MOVEMENT_MEDITATION",
	MANTRA_MEDITATION = "MANTRA_MEDITATION",
	TRANSCENDENTAL_MEDITATION = "TRANSCENDENTAL_MEDITATION",
	PROGRESSIVE_RELAXATION = "PROGRESSIVE_RELAXATION",
	LOVING_KINDNESS_MEDITATION = "LOVING_KINDNESS_MEDITATION",
	THINKING = "THINKING",
	SOUND_AIDS = "SOUND_AIDS",
	MONITORING_YOUR_SLEEP = "MONITORING_YOUR_SLEEP",
	ANTI_SNORING_SOLUTIONS = "ANTI_SNORING_SOLUTIONS",
	SLEEP_COACHING = "SLEEP_COACHING",
	SLEEPING_AIDS = "SLEEPING_AIDS",
	SLEEP_WELL = "SLEEP_WELL",
	LIVE_CLASS = "LIVE_CLASS",
	FLEXIBILITY = "FLEXIBILITY",
	STRETCHING = "STRETCHING",
	RELIEVE_BODY_PAIN = "RELIEVE_BODY_PAIN",
	BETTER_POSTURE = "BETTER_POSTURE",
	PHYSIO = "PHYSIO",
	HEALTHY_DIET = "HEALTHY_DIET",
	NUTRITIONIST = "NUTRITIONIST",
	DIET_PLAN_REVIEWER = "DIET_PLAN_REVIEWER",
	LOOSE_WEIGHT = "LOOSE_WEIGHT",
	BETTER_HEALTH = "BETTER_HEALTH",
	OPTIMUM_NUTRITION = "OPTIMUM_NUTRITION",
	BE_ENERGETIC = "BE_ENERGETIC",
	REDUCE_HEALTH_RISK = "REDUCE_HEALTH_RISK",
	DIETITIAN = "DIETIATION",
}

// Report
export enum ReportCategory {
	USER = "USER",
	HOST = "HOST",
	REVENUE = "REVENUE",
	COMMISSION = "COMMISSION",
}

export enum ReportSubCategory {
	COUNT = "COUNT",
	LIVE_CLASS = "LIVE_CLASS",
	WORKSHOP = "WORKSHOP",
	APPOINTMENTS = "APPOINTMENTS",
	PAID_VIDEOS = "PAID_VIDEOS",
	// 3rd party
	HEALTH_VECTOR = "HEALTH_VECTOR",
	SONDE = "SONDE",
	ANURA = "ANURA",
}

export enum ReportCommission {
	WORKSHOP = "WORKSHOP",
	LIVE_CLASS = "LIVE_CLASS",
	APPOINTMENTS = "APPOINTMENTS",
	PAID_VIDEOS = "PAID_VIDEOS",
}

export enum ReportRevenue {
	WORKSHOP = "WORKSHOP",
	LIVE_CLASS = "LIVE_CLASS",
	APPOINTMENTS = "APPOINTMENTS",
	PAID_VIDEOS = "PAID_VIDEOS",
	// 3rd party
	HEALTH_VECTOR = "HEALTH_VECTOR",
	SONDE = "SONDE",
	ANURA = "ANURA",
}

export enum ReportRevenueMove {
	WORKSHOP = "WORKSHOP",
	LIVE_CLASS = "LIVE_CLASS",
}

export enum ReportRevenueHost {
	WORKSHOP = "WORKSHOP",
}

export enum ReportThirdParty {
	HEALTH_VECTOR = "HEALTH_VECTOR",
	SONDE = "SONDE",
	ANURA = "ANURA",
}

export enum ReportName {
	WORKSHOP = "Workshop",
	LIVE_CLASS = "Live Class",
	APPOINTMENTS = "Appointments",
	PAID_VIDEOS = "Paid Videos",
	// 3rd party
	HEALTH_VECTOR = "Health Vector",
	SONDE = "Sonde",
	ANURA = "Anura",
}

// Report Count
export enum ReportCountEnum {
	SUBSCRIPTION = "SUBSCRIPTION",
	CMS_PROMOTION = "CMS_PROMOTION",
	CMS_CONTENT = "CMS_CONTENT",
	CMS_SERIES = "CMS_SERIES",
}

// scan
export enum ScanActivityEnum {
	AWAITING_SCAN = "AWAITING_SCAN",
	CANCEL = "CANCEL",
	SUCCESS = "SUCCESS",
}

export enum LoginTypeEnum {
	EMAIL = "EMAIL",
	PHONE_NUMBER = "PHONE_NUMBER",
	GOOGLE = "GOOGLE",
	FACEBOOK = "FACEBOOK",
	INSTAGRAM = "INSTAGRAM",
	APPLE = "APPLE",
}

export enum SubscribableEntityTypeEnum {
	EVENT = "EVENT",
	EVENT_TRIAL = "EVENT_TRAIL",
	SUBSCRIPTION_PLANS = "SUBSCRIPTION_PLANS",
	PRICING = "PRICING",
}

// Revenue
export enum RevenueEnumMove {
	REVENUE = "REVENUE",
	LIVE_CLASS = "LIVE_CLASS",
	WORKSHOP = "WORKSHOP",
}

export enum RevenueEnumHost {
	REVENUE = "REVENUE",
	WORKSHOP = "WORKSHOP",
}

export enum RevenueEnumTitle {
	REVENUE = "Revenue",
	LIVE_CLASS = "Live Class",
	WORKSHOP = "Workshop",
}

// Tags
export enum TagsTypeEnum {
	APP = "APP",
	SONDE = "SONDE",
	THINK_RIGHT_ASSESSMENT = "THINK_RIGHT_ASSESSMENT",
	SLEEP_RIGHT_ASSESSMENT = "SLEEP_RIGHT_ASSESSMENT",
}

// Stats
export enum StatisticsCategory {
	USER_STATS = "USER_STATS",
	HOST_STATS = "HOST_STATS",
}

export enum StatisticsSubCategory {
	WELLNESS_DAYS = "WELLNESS_DAYS",
	DAILY_JOURNALS = "DAILY_JOURNALS",
	MY_MOOD = "MY_MOOD", //voice scan
	AFFIRMATION = "AFFIRMATION",
	MEAL_PLAN = "MEAL_PLAN",
	HEALTH_REPORT = "HEALTH_REPORT",
	RECIPES_VIEWED = "RECIPES_VIEWED",
	NIGHT_SOUNDS = "NIGHT_SOUNDS",
	FACIAL_SCAN = "FACIAL_SCAN",
	MARKED_MEAL_PLAN = "MARKED_MEAL_PLAN",
}

export enum MyStatsTemplates {
	MY_PROGRESS = "MY_PROGRESS",
	WORKSHOP = "WORKSHOP",
	LIVE_EVENT = "LIVE_EVENT",
}

export enum Status {
	ADDED = "ADDED",
	REMOVED = "REMOVED",
}

export enum DeviceType {
	WEB = "web",
	ANDROID = "android",
	IOS = "ios",
}

export enum DeviceStatusForConference {
	ACTIVE = "ACTIVE",
	DELETE = "DELETE",
}

// App: Modules
export enum AppServicesEnum {
	DIET_PLAN = "DIET_PLAN",
	HEALTH_REPORT = "HEALTH_REPORT",
	CHECK_IN = "CHECK_IN",
	FACIAL_SCAN = "FACIAL_SCAN",
	LIVE_CLASS = "LIVE_CLASS",
	WORKSHOP = "WORKSHOP",
	AFFIRMATION = "AFFIRMATION",
	PAID_CONTENT = "PAID_CONTENT",
	JOURNALLING = "JOURNALLING",
	PSYCH_AUDIT = "PSYCH_AUDIT",
	SLEEP_AUDIT = "SLEEP_AUDIT",
	SLEEP_SOUNDS = "SLEEP_SOUNDS",
	GUIDED_MEDITATION = "GUIDED_MEDITATION",
	MIND_AUDIT = "MIND_AUDIT",
	BUNDLE = "BUNDLE",
}

export enum AppModuleTypeEnum {
	MODULE = "MODULE",
	CATEGORY = "CATEGORY",
}

// App: Analytics
export enum AnalyticsCategory {
	CONTENT = "CONTENT",
	EPISODE = "EPISODE",
	EVENT = "EVENT",
	SERVICE = "SERVICE",
}
export enum AnalyticsSubCategory {
	CLICKED = "CLICKED",
	WATCHED = "WATCHED",
}
